#!/bin/bash

PERSON1=$1
PERSON2=$2

echo "$PERSON1 : HEYY! $PERSON2 WASSUP"
echo "$PERSON2 : NTG MUCH. WAU? $PERSON1"
echo "$PERSON1 : WHAT ARE YOUR PLANS TODAY $PERSON2"
echo "$PERSON2 : IM GOT AN INVITATION FOR TWO BRUNCHES $PERSON1"